# Generated by Django 3.1.5 on 2021-01-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('R', 'Residential'), ('C', 'Commercial')], max_length=1)),
                ('heat_type', models.CharField(choices=[('NGS', 'NaturalGas'), ('OIL', 'Oil'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('vehicle_type', models.CharField(choices=[('D', 'Diesel'), ('G', 'Gas')], default='G', max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('lattitude', models.FloatField()),
                ('heat', models.FloatField()),
                ('vehicle', models.FloatField()),
                ('electricity', models.FloatField()),
                ('air', models.FloatField()),
                ('rail', models.FloatField()),
                ('emissions_total', models.FloatField(null=True)),
            ],
        ),
    ]
